
// components/ProImageGen.tsx
/**
 * @file Interfaz de usuario para el "Pro Image Gen Studio".
 * Permite a los usuarios crear imágenes con control granular sobre el prompt,
 * la relación de aspecto y la resolución.
 */

import React from 'react';
import { useImageGeneratorState } from '../hooks/useImageGeneratorState';
import { ImageConfig } from '../types';

// Opciones extraídas directamente del tipo para mantener la consistencia.
const aspectRatios: ImageConfig['aspectRatio'][] = ['1:1', '2:3', '3:2', '3:4', '4:3', '16:9', '21:9'];
const resolutions: ImageConfig['resolution'][] = ['1K', '2K', '4K'];

export const ProImageGen: React.FC = () => {
    const { 
        prompt, 
        aspectRatio, 
        resolution, 
        isLoading, 
        error, 
        generatedImage, 
        setGeneratorOption, 
        runImageGeneration 
    } = useImageGeneratorState();

    const handleGenerate = (e: React.FormEvent) => {
        e.preventDefault();
        runImageGeneration();
    };

    return (
        <div className="pro-image-gen-studio">
            <header className="studio-header">
                <h1>Pro Image Gen Studio</h1>
                <p>Generación de imágenes de alta fidelidad con control avanzado.</p>
            </header>
            
            <form onSubmit={handleGenerate} className="studio-controls">
                <div className="prompt-section">
                    <label htmlFor="prompt-input">Prompt Detallado</label>
                    <textarea
                        id="prompt-input"
                        value={prompt}
                        onChange={(e) => setGeneratorOption('prompt', e.target.value)}
                        placeholder="Ej: A cinematic shot of a futuristic cyberpunk city at night, intricate details, neon lights, rain..."
                        disabled={isLoading}
                    />
                </div>
                
                <div className="config-section">
                    <div className="select-group">
                        <label htmlFor="aspect-ratio-select">Aspect Ratio</label>
                        <select
                            id="aspect-ratio-select"
                            value={aspectRatio}
                            onChange={(e) => setGeneratorOption('aspectRatio', e.target.value as ImageConfig['aspectRatio'])}
                            disabled={isLoading}
                        >
                            {aspectRatios.map(ar => <option key={ar} value={ar}>{ar}</option>)}
                        </select>
                    </div>
                    
                    <div className="select-group">
                        <label htmlFor="resolution-select">Resolución</label>
                        <select
                            id="resolution-select"
                            value={resolution}
                            onChange={(e) => setGeneratorOption('resolution', e.target.value as ImageConfig['resolution'])}
                            disabled={isLoading}
                        >
                            {resolutions.map(res => <option key={res} value={res}>{res}</option>)}
                        </select>
                    </div>
                </div>

                <button type="submit" className="generate-button" disabled={isLoading}>
                    {isLoading ? 'Generando...' : 'Generate Image'}
                </button>
            </form>

            {error && (
                <div className="studio-result error-display">
                    <strong>Error:</strong> {error.message}
                </div>
            )}

            {generatedImage && (
                <div className="studio-result image-display">
                    <img src={generatedImage} alt="Generated by Gemini" />
                </div>
            )}
        </div>
    );
};
